# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PvaultServer < Formula
  desc ""
  homepage "https://piiano.com"
  version "1.11.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/piiano/vault-releases/releases/download/v1.11.0/pvault-server-v1.11.0-darwin_arm64.tar.gz"
      sha256 "4ecd7e984cc1324b227d2d1c0daeb1049a697dd85c045712536aba36602a8bfc"

      def install
        bin.install "pvault-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/piiano/vault-releases/releases/download/v1.11.0/pvault-server-v1.11.0-darwin_amd64.tar.gz"
      sha256 "cfa8514a8148a5873d2e8c1498918c0b1a5a2503a0fa50653d8c15b96b0daaf8"

      def install
        bin.install "pvault-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/piiano/vault-releases/releases/download/v1.11.0/pvault-server-v1.11.0-linux_arm64.tar.gz"
      sha256 "21fc0671c6b1bec8a16442b138a767db0c8207b6701ff77be9968296f60494c7"

      def install
        bin.install "pvault-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/piiano/vault-releases/releases/download/v1.11.0/pvault-server-v1.11.0-linux_amd64.tar.gz"
      sha256 "1687911df7e73c70d709530c39625918bffffc98d3c6f95f55d7558f7e2935f3"

      def install
        bin.install "pvault-server"
      end
    end
  end
end
