# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PvaultServer < Formula
  desc ""
  homepage "https://piiano.com"
  version "1.10.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/piiano/vault-releases/releases/download/v1.10.2/pvault-server-v1.10.2-darwin_amd64.tar.gz"
      sha256 "d1ecc38ca568d1e6846c7d1d2403a58815e1e5028bca2b09d0a9d171f347f384"

      def install
        bin.install "pvault-server"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/piiano/vault-releases/releases/download/v1.10.2/pvault-server-v1.10.2-darwin_arm64.tar.gz"
      sha256 "1a0da3ae208fe751424d486bce256d0cd3dbee30c778b00c27d1511be9e48f92"

      def install
        bin.install "pvault-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/piiano/vault-releases/releases/download/v1.10.2/pvault-server-v1.10.2-linux_arm64.tar.gz"
      sha256 "89b7cd7d5b479f80c3bdf610e3e6ad12294dc021e056af8d01848a41626aeb15"

      def install
        bin.install "pvault-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/piiano/vault-releases/releases/download/v1.10.2/pvault-server-v1.10.2-linux_amd64.tar.gz"
      sha256 "351eeadc9bfab713327566a54f62773a7727c30659701ae33a4d8fab524b6b6f"

      def install
        bin.install "pvault-server"
      end
    end
  end
end
